package com.sjjybsgj.stardard_table.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class StardardTableExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stardard_table
     *
     * @mbg.generated Sun May 27 19:04:09 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stardard_table
     *
     * @mbg.generated Sun May 27 19:04:09 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table stardard_table
     *
     * @mbg.generated Sun May 27 19:04:09 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stardard_table
     *
     * @mbg.generated Sun May 27 19:04:09 CST 2018
     */
    public StardardTableExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stardard_table
     *
     * @mbg.generated Sun May 27 19:04:09 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stardard_table
     *
     * @mbg.generated Sun May 27 19:04:09 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stardard_table
     *
     * @mbg.generated Sun May 27 19:04:09 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stardard_table
     *
     * @mbg.generated Sun May 27 19:04:09 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stardard_table
     *
     * @mbg.generated Sun May 27 19:04:09 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stardard_table
     *
     * @mbg.generated Sun May 27 19:04:09 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stardard_table
     *
     * @mbg.generated Sun May 27 19:04:09 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stardard_table
     *
     * @mbg.generated Sun May 27 19:04:09 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stardard_table
     *
     * @mbg.generated Sun May 27 19:04:09 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stardard_table
     *
     * @mbg.generated Sun May 27 19:04:09 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table stardard_table
     *
     * @mbg.generated Sun May 27 19:04:09 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andColumnRuleIdIsNull() {
            addCriterion("COLUMN_RULE_ID is null");
            return (Criteria) this;
        }

        public Criteria andColumnRuleIdIsNotNull() {
            addCriterion("COLUMN_RULE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andColumnRuleIdEqualTo(String value) {
            addCriterion("COLUMN_RULE_ID =", value, "columnRuleId");
            return (Criteria) this;
        }

        public Criteria andColumnRuleIdNotEqualTo(String value) {
            addCriterion("COLUMN_RULE_ID <>", value, "columnRuleId");
            return (Criteria) this;
        }

        public Criteria andColumnRuleIdGreaterThan(String value) {
            addCriterion("COLUMN_RULE_ID >", value, "columnRuleId");
            return (Criteria) this;
        }

        public Criteria andColumnRuleIdGreaterThanOrEqualTo(String value) {
            addCriterion("COLUMN_RULE_ID >=", value, "columnRuleId");
            return (Criteria) this;
        }

        public Criteria andColumnRuleIdLessThan(String value) {
            addCriterion("COLUMN_RULE_ID <", value, "columnRuleId");
            return (Criteria) this;
        }

        public Criteria andColumnRuleIdLessThanOrEqualTo(String value) {
            addCriterion("COLUMN_RULE_ID <=", value, "columnRuleId");
            return (Criteria) this;
        }

        public Criteria andColumnRuleIdLike(String value) {
            addCriterion("COLUMN_RULE_ID like", value, "columnRuleId");
            return (Criteria) this;
        }

        public Criteria andColumnRuleIdNotLike(String value) {
            addCriterion("COLUMN_RULE_ID not like", value, "columnRuleId");
            return (Criteria) this;
        }

        public Criteria andColumnRuleIdIn(List<String> values) {
            addCriterion("COLUMN_RULE_ID in", values, "columnRuleId");
            return (Criteria) this;
        }

        public Criteria andColumnRuleIdNotIn(List<String> values) {
            addCriterion("COLUMN_RULE_ID not in", values, "columnRuleId");
            return (Criteria) this;
        }

        public Criteria andColumnRuleIdBetween(String value1, String value2) {
            addCriterion("COLUMN_RULE_ID between", value1, value2, "columnRuleId");
            return (Criteria) this;
        }

        public Criteria andColumnRuleIdNotBetween(String value1, String value2) {
            addCriterion("COLUMN_RULE_ID not between", value1, value2, "columnRuleId");
            return (Criteria) this;
        }

        public Criteria andDbNameIsNull() {
            addCriterion("DB_NAME is null");
            return (Criteria) this;
        }

        public Criteria andDbNameIsNotNull() {
            addCriterion("DB_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andDbNameEqualTo(String value) {
            addCriterion("DB_NAME =", value, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbNameNotEqualTo(String value) {
            addCriterion("DB_NAME <>", value, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbNameGreaterThan(String value) {
            addCriterion("DB_NAME >", value, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbNameGreaterThanOrEqualTo(String value) {
            addCriterion("DB_NAME >=", value, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbNameLessThan(String value) {
            addCriterion("DB_NAME <", value, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbNameLessThanOrEqualTo(String value) {
            addCriterion("DB_NAME <=", value, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbNameLike(String value) {
            addCriterion("DB_NAME like", value, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbNameNotLike(String value) {
            addCriterion("DB_NAME not like", value, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbNameIn(List<String> values) {
            addCriterion("DB_NAME in", values, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbNameNotIn(List<String> values) {
            addCriterion("DB_NAME not in", values, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbNameBetween(String value1, String value2) {
            addCriterion("DB_NAME between", value1, value2, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbNameNotBetween(String value1, String value2) {
            addCriterion("DB_NAME not between", value1, value2, "dbName");
            return (Criteria) this;
        }

        public Criteria andTableCodeIsNull() {
            addCriterion("TABLE_CODE is null");
            return (Criteria) this;
        }

        public Criteria andTableCodeIsNotNull() {
            addCriterion("TABLE_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andTableCodeEqualTo(String value) {
            addCriterion("TABLE_CODE =", value, "tableCode");
            return (Criteria) this;
        }

        public Criteria andTableCodeNotEqualTo(String value) {
            addCriterion("TABLE_CODE <>", value, "tableCode");
            return (Criteria) this;
        }

        public Criteria andTableCodeGreaterThan(String value) {
            addCriterion("TABLE_CODE >", value, "tableCode");
            return (Criteria) this;
        }

        public Criteria andTableCodeGreaterThanOrEqualTo(String value) {
            addCriterion("TABLE_CODE >=", value, "tableCode");
            return (Criteria) this;
        }

        public Criteria andTableCodeLessThan(String value) {
            addCriterion("TABLE_CODE <", value, "tableCode");
            return (Criteria) this;
        }

        public Criteria andTableCodeLessThanOrEqualTo(String value) {
            addCriterion("TABLE_CODE <=", value, "tableCode");
            return (Criteria) this;
        }

        public Criteria andTableCodeLike(String value) {
            addCriterion("TABLE_CODE like", value, "tableCode");
            return (Criteria) this;
        }

        public Criteria andTableCodeNotLike(String value) {
            addCriterion("TABLE_CODE not like", value, "tableCode");
            return (Criteria) this;
        }

        public Criteria andTableCodeIn(List<String> values) {
            addCriterion("TABLE_CODE in", values, "tableCode");
            return (Criteria) this;
        }

        public Criteria andTableCodeNotIn(List<String> values) {
            addCriterion("TABLE_CODE not in", values, "tableCode");
            return (Criteria) this;
        }

        public Criteria andTableCodeBetween(String value1, String value2) {
            addCriterion("TABLE_CODE between", value1, value2, "tableCode");
            return (Criteria) this;
        }

        public Criteria andTableCodeNotBetween(String value1, String value2) {
            addCriterion("TABLE_CODE not between", value1, value2, "tableCode");
            return (Criteria) this;
        }

        public Criteria andTableNameIsNull() {
            addCriterion("TABLE_NAME is null");
            return (Criteria) this;
        }

        public Criteria andTableNameIsNotNull() {
            addCriterion("TABLE_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andTableNameEqualTo(String value) {
            addCriterion("TABLE_NAME =", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameNotEqualTo(String value) {
            addCriterion("TABLE_NAME <>", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameGreaterThan(String value) {
            addCriterion("TABLE_NAME >", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameGreaterThanOrEqualTo(String value) {
            addCriterion("TABLE_NAME >=", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameLessThan(String value) {
            addCriterion("TABLE_NAME <", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameLessThanOrEqualTo(String value) {
            addCriterion("TABLE_NAME <=", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameLike(String value) {
            addCriterion("TABLE_NAME like", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameNotLike(String value) {
            addCriterion("TABLE_NAME not like", value, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameIn(List<String> values) {
            addCriterion("TABLE_NAME in", values, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameNotIn(List<String> values) {
            addCriterion("TABLE_NAME not in", values, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameBetween(String value1, String value2) {
            addCriterion("TABLE_NAME between", value1, value2, "tableName");
            return (Criteria) this;
        }

        public Criteria andTableNameNotBetween(String value1, String value2) {
            addCriterion("TABLE_NAME not between", value1, value2, "tableName");
            return (Criteria) this;
        }

        public Criteria andColumnNameIsNull() {
            addCriterion("COLUMN_NAME is null");
            return (Criteria) this;
        }

        public Criteria andColumnNameIsNotNull() {
            addCriterion("COLUMN_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andColumnNameEqualTo(String value) {
            addCriterion("COLUMN_NAME =", value, "columnName");
            return (Criteria) this;
        }

        public Criteria andColumnNameNotEqualTo(String value) {
            addCriterion("COLUMN_NAME <>", value, "columnName");
            return (Criteria) this;
        }

        public Criteria andColumnNameGreaterThan(String value) {
            addCriterion("COLUMN_NAME >", value, "columnName");
            return (Criteria) this;
        }

        public Criteria andColumnNameGreaterThanOrEqualTo(String value) {
            addCriterion("COLUMN_NAME >=", value, "columnName");
            return (Criteria) this;
        }

        public Criteria andColumnNameLessThan(String value) {
            addCriterion("COLUMN_NAME <", value, "columnName");
            return (Criteria) this;
        }

        public Criteria andColumnNameLessThanOrEqualTo(String value) {
            addCriterion("COLUMN_NAME <=", value, "columnName");
            return (Criteria) this;
        }

        public Criteria andColumnNameLike(String value) {
            addCriterion("COLUMN_NAME like", value, "columnName");
            return (Criteria) this;
        }

        public Criteria andColumnNameNotLike(String value) {
            addCriterion("COLUMN_NAME not like", value, "columnName");
            return (Criteria) this;
        }

        public Criteria andColumnNameIn(List<String> values) {
            addCriterion("COLUMN_NAME in", values, "columnName");
            return (Criteria) this;
        }

        public Criteria andColumnNameNotIn(List<String> values) {
            addCriterion("COLUMN_NAME not in", values, "columnName");
            return (Criteria) this;
        }

        public Criteria andColumnNameBetween(String value1, String value2) {
            addCriterion("COLUMN_NAME between", value1, value2, "columnName");
            return (Criteria) this;
        }

        public Criteria andColumnNameNotBetween(String value1, String value2) {
            addCriterion("COLUMN_NAME not between", value1, value2, "columnName");
            return (Criteria) this;
        }

        public Criteria andColumnIndexIsNull() {
            addCriterion("COLUMN_INDEX is null");
            return (Criteria) this;
        }

        public Criteria andColumnIndexIsNotNull() {
            addCriterion("COLUMN_INDEX is not null");
            return (Criteria) this;
        }

        public Criteria andColumnIndexEqualTo(Integer value) {
            addCriterion("COLUMN_INDEX =", value, "columnIndex");
            return (Criteria) this;
        }

        public Criteria andColumnIndexNotEqualTo(Integer value) {
            addCriterion("COLUMN_INDEX <>", value, "columnIndex");
            return (Criteria) this;
        }

        public Criteria andColumnIndexGreaterThan(Integer value) {
            addCriterion("COLUMN_INDEX >", value, "columnIndex");
            return (Criteria) this;
        }

        public Criteria andColumnIndexGreaterThanOrEqualTo(Integer value) {
            addCriterion("COLUMN_INDEX >=", value, "columnIndex");
            return (Criteria) this;
        }

        public Criteria andColumnIndexLessThan(Integer value) {
            addCriterion("COLUMN_INDEX <", value, "columnIndex");
            return (Criteria) this;
        }

        public Criteria andColumnIndexLessThanOrEqualTo(Integer value) {
            addCriterion("COLUMN_INDEX <=", value, "columnIndex");
            return (Criteria) this;
        }

        public Criteria andColumnIndexIn(List<Integer> values) {
            addCriterion("COLUMN_INDEX in", values, "columnIndex");
            return (Criteria) this;
        }

        public Criteria andColumnIndexNotIn(List<Integer> values) {
            addCriterion("COLUMN_INDEX not in", values, "columnIndex");
            return (Criteria) this;
        }

        public Criteria andColumnIndexBetween(Integer value1, Integer value2) {
            addCriterion("COLUMN_INDEX between", value1, value2, "columnIndex");
            return (Criteria) this;
        }

        public Criteria andColumnIndexNotBetween(Integer value1, Integer value2) {
            addCriterion("COLUMN_INDEX not between", value1, value2, "columnIndex");
            return (Criteria) this;
        }

        public Criteria andColumnTypeIsNull() {
            addCriterion("COLUMN_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andColumnTypeIsNotNull() {
            addCriterion("COLUMN_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andColumnTypeEqualTo(String value) {
            addCriterion("COLUMN_TYPE =", value, "columnType");
            return (Criteria) this;
        }

        public Criteria andColumnTypeNotEqualTo(String value) {
            addCriterion("COLUMN_TYPE <>", value, "columnType");
            return (Criteria) this;
        }

        public Criteria andColumnTypeGreaterThan(String value) {
            addCriterion("COLUMN_TYPE >", value, "columnType");
            return (Criteria) this;
        }

        public Criteria andColumnTypeGreaterThanOrEqualTo(String value) {
            addCriterion("COLUMN_TYPE >=", value, "columnType");
            return (Criteria) this;
        }

        public Criteria andColumnTypeLessThan(String value) {
            addCriterion("COLUMN_TYPE <", value, "columnType");
            return (Criteria) this;
        }

        public Criteria andColumnTypeLessThanOrEqualTo(String value) {
            addCriterion("COLUMN_TYPE <=", value, "columnType");
            return (Criteria) this;
        }

        public Criteria andColumnTypeLike(String value) {
            addCriterion("COLUMN_TYPE like", value, "columnType");
            return (Criteria) this;
        }

        public Criteria andColumnTypeNotLike(String value) {
            addCriterion("COLUMN_TYPE not like", value, "columnType");
            return (Criteria) this;
        }

        public Criteria andColumnTypeIn(List<String> values) {
            addCriterion("COLUMN_TYPE in", values, "columnType");
            return (Criteria) this;
        }

        public Criteria andColumnTypeNotIn(List<String> values) {
            addCriterion("COLUMN_TYPE not in", values, "columnType");
            return (Criteria) this;
        }

        public Criteria andColumnTypeBetween(String value1, String value2) {
            addCriterion("COLUMN_TYPE between", value1, value2, "columnType");
            return (Criteria) this;
        }

        public Criteria andColumnTypeNotBetween(String value1, String value2) {
            addCriterion("COLUMN_TYPE not between", value1, value2, "columnType");
            return (Criteria) this;
        }

        public Criteria andPostionIsNull() {
            addCriterion("POSTION is null");
            return (Criteria) this;
        }

        public Criteria andPostionIsNotNull() {
            addCriterion("POSTION is not null");
            return (Criteria) this;
        }

        public Criteria andPostionEqualTo(String value) {
            addCriterion("POSTION =", value, "postion");
            return (Criteria) this;
        }

        public Criteria andPostionNotEqualTo(String value) {
            addCriterion("POSTION <>", value, "postion");
            return (Criteria) this;
        }

        public Criteria andPostionGreaterThan(String value) {
            addCriterion("POSTION >", value, "postion");
            return (Criteria) this;
        }

        public Criteria andPostionGreaterThanOrEqualTo(String value) {
            addCriterion("POSTION >=", value, "postion");
            return (Criteria) this;
        }

        public Criteria andPostionLessThan(String value) {
            addCriterion("POSTION <", value, "postion");
            return (Criteria) this;
        }

        public Criteria andPostionLessThanOrEqualTo(String value) {
            addCriterion("POSTION <=", value, "postion");
            return (Criteria) this;
        }

        public Criteria andPostionLike(String value) {
            addCriterion("POSTION like", value, "postion");
            return (Criteria) this;
        }

        public Criteria andPostionNotLike(String value) {
            addCriterion("POSTION not like", value, "postion");
            return (Criteria) this;
        }

        public Criteria andPostionIn(List<String> values) {
            addCriterion("POSTION in", values, "postion");
            return (Criteria) this;
        }

        public Criteria andPostionNotIn(List<String> values) {
            addCriterion("POSTION not in", values, "postion");
            return (Criteria) this;
        }

        public Criteria andPostionBetween(String value1, String value2) {
            addCriterion("POSTION between", value1, value2, "postion");
            return (Criteria) this;
        }

        public Criteria andPostionNotBetween(String value1, String value2) {
            addCriterion("POSTION not between", value1, value2, "postion");
            return (Criteria) this;
        }

        public Criteria andCloumnCommentIsNull() {
            addCriterion("CLOUMN_COMMENT is null");
            return (Criteria) this;
        }

        public Criteria andCloumnCommentIsNotNull() {
            addCriterion("CLOUMN_COMMENT is not null");
            return (Criteria) this;
        }

        public Criteria andCloumnCommentEqualTo(String value) {
            addCriterion("CLOUMN_COMMENT =", value, "cloumnComment");
            return (Criteria) this;
        }

        public Criteria andCloumnCommentNotEqualTo(String value) {
            addCriterion("CLOUMN_COMMENT <>", value, "cloumnComment");
            return (Criteria) this;
        }

        public Criteria andCloumnCommentGreaterThan(String value) {
            addCriterion("CLOUMN_COMMENT >", value, "cloumnComment");
            return (Criteria) this;
        }

        public Criteria andCloumnCommentGreaterThanOrEqualTo(String value) {
            addCriterion("CLOUMN_COMMENT >=", value, "cloumnComment");
            return (Criteria) this;
        }

        public Criteria andCloumnCommentLessThan(String value) {
            addCriterion("CLOUMN_COMMENT <", value, "cloumnComment");
            return (Criteria) this;
        }

        public Criteria andCloumnCommentLessThanOrEqualTo(String value) {
            addCriterion("CLOUMN_COMMENT <=", value, "cloumnComment");
            return (Criteria) this;
        }

        public Criteria andCloumnCommentLike(String value) {
            addCriterion("CLOUMN_COMMENT like", value, "cloumnComment");
            return (Criteria) this;
        }

        public Criteria andCloumnCommentNotLike(String value) {
            addCriterion("CLOUMN_COMMENT not like", value, "cloumnComment");
            return (Criteria) this;
        }

        public Criteria andCloumnCommentIn(List<String> values) {
            addCriterion("CLOUMN_COMMENT in", values, "cloumnComment");
            return (Criteria) this;
        }

        public Criteria andCloumnCommentNotIn(List<String> values) {
            addCriterion("CLOUMN_COMMENT not in", values, "cloumnComment");
            return (Criteria) this;
        }

        public Criteria andCloumnCommentBetween(String value1, String value2) {
            addCriterion("CLOUMN_COMMENT between", value1, value2, "cloumnComment");
            return (Criteria) this;
        }

        public Criteria andCloumnCommentNotBetween(String value1, String value2) {
            addCriterion("CLOUMN_COMMENT not between", value1, value2, "cloumnComment");
            return (Criteria) this;
        }

        public Criteria andRuleDateIsNull() {
            addCriterion("RULE_DATE is null");
            return (Criteria) this;
        }

        public Criteria andRuleDateIsNotNull() {
            addCriterion("RULE_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andRuleDateEqualTo(Date value) {
            addCriterion("RULE_DATE =", value, "ruleDate");
            return (Criteria) this;
        }

        public Criteria andRuleDateNotEqualTo(Date value) {
            addCriterion("RULE_DATE <>", value, "ruleDate");
            return (Criteria) this;
        }

        public Criteria andRuleDateGreaterThan(Date value) {
            addCriterion("RULE_DATE >", value, "ruleDate");
            return (Criteria) this;
        }

        public Criteria andRuleDateGreaterThanOrEqualTo(Date value) {
            addCriterion("RULE_DATE >=", value, "ruleDate");
            return (Criteria) this;
        }

        public Criteria andRuleDateLessThan(Date value) {
            addCriterion("RULE_DATE <", value, "ruleDate");
            return (Criteria) this;
        }

        public Criteria andRuleDateLessThanOrEqualTo(Date value) {
            addCriterion("RULE_DATE <=", value, "ruleDate");
            return (Criteria) this;
        }

        public Criteria andRuleDateIn(List<Date> values) {
            addCriterion("RULE_DATE in", values, "ruleDate");
            return (Criteria) this;
        }

        public Criteria andRuleDateNotIn(List<Date> values) {
            addCriterion("RULE_DATE not in", values, "ruleDate");
            return (Criteria) this;
        }

        public Criteria andRuleDateBetween(Date value1, Date value2) {
            addCriterion("RULE_DATE between", value1, value2, "ruleDate");
            return (Criteria) this;
        }

        public Criteria andRuleDateNotBetween(Date value1, Date value2) {
            addCriterion("RULE_DATE not between", value1, value2, "ruleDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table stardard_table
     *
     * @mbg.generated do_not_delete_during_merge Sun May 27 19:04:09 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table stardard_table
     *
     * @mbg.generated Sun May 27 19:04:09 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}