package com.sjjybsgj.stardard_table.mapper;

import com.sjjybsgj.stardard_table.model.StardardTable;
import com.sjjybsgj.stardard_table.model.StardardTableExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StardardTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stardard_table
     *
     * @mbg.generated Sun May 27 19:04:09 CST 2018
     */
    long countByExample(StardardTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stardard_table
     *
     * @mbg.generated Sun May 27 19:04:09 CST 2018
     */
    int deleteByExample(StardardTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stardard_table
     *
     * @mbg.generated Sun May 27 19:04:09 CST 2018
     */
    int deleteByPrimaryKey(String columnRuleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stardard_table
     *
     * @mbg.generated Sun May 27 19:04:09 CST 2018
     */
    int insert(StardardTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stardard_table
     *
     * @mbg.generated Sun May 27 19:04:09 CST 2018
     */
    int insertSelective(StardardTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stardard_table
     *
     * @mbg.generated Sun May 27 19:04:09 CST 2018
     */
    List<StardardTable> selectByExample(StardardTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stardard_table
     *
     * @mbg.generated Sun May 27 19:04:09 CST 2018
     */
    StardardTable selectByPrimaryKey(String columnRuleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stardard_table
     *
     * @mbg.generated Sun May 27 19:04:09 CST 2018
     */
    int updateByExampleSelective(@Param("record") StardardTable record, @Param("example") StardardTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stardard_table
     *
     * @mbg.generated Sun May 27 19:04:09 CST 2018
     */
    int updateByExample(@Param("record") StardardTable record, @Param("example") StardardTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stardard_table
     *
     * @mbg.generated Sun May 27 19:04:09 CST 2018
     */
    int updateByPrimaryKeySelective(StardardTable record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stardard_table
     *
     * @mbg.generated Sun May 27 19:04:09 CST 2018
     */
    int updateByPrimaryKey(StardardTable record);
}