package com.sjjybsgj.rule_table.mapper;

import com.sjjybsgj.rule_table.model.RuleTable;
import com.sjjybsgj.rule_table.model.RuleTableExample;
import com.sjjybsgj.rule_table.model.RuleTableWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RuleTableMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_table
     *
     * @mbg.generated Mon May 28 15:03:50 CST 2018
     */
    long countByExample(RuleTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_table
     *
     * @mbg.generated Mon May 28 15:03:50 CST 2018
     */
    int deleteByExample(RuleTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_table
     *
     * @mbg.generated Mon May 28 15:03:50 CST 2018
     */
    int deleteByPrimaryKey(String ruleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_table
     *
     * @mbg.generated Mon May 28 15:03:50 CST 2018
     */
    int insert(RuleTableWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_table
     *
     * @mbg.generated Mon May 28 15:03:50 CST 2018
     */
    int insertSelective(RuleTableWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_table
     *
     * @mbg.generated Mon May 28 15:03:50 CST 2018
     */
    List<RuleTableWithBLOBs> selectByExampleWithBLOBs(RuleTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_table
     *
     * @mbg.generated Mon May 28 15:03:50 CST 2018
     */
    List<RuleTable> selectByExample(RuleTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_table
     *
     * @mbg.generated Mon May 28 15:03:50 CST 2018
     */
    RuleTableWithBLOBs selectByPrimaryKey(String ruleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_table
     *
     * @mbg.generated Mon May 28 15:03:50 CST 2018
     */
    int updateByExampleSelective(@Param("record") RuleTableWithBLOBs record, @Param("example") RuleTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_table
     *
     * @mbg.generated Mon May 28 15:03:50 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") RuleTableWithBLOBs record, @Param("example") RuleTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_table
     *
     * @mbg.generated Mon May 28 15:03:50 CST 2018
     */
    int updateByExample(@Param("record") RuleTable record, @Param("example") RuleTableExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_table
     *
     * @mbg.generated Mon May 28 15:03:50 CST 2018
     */
    int updateByPrimaryKeySelective(RuleTableWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_table
     *
     * @mbg.generated Mon May 28 15:03:50 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(RuleTableWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_table
     *
     * @mbg.generated Mon May 28 15:03:50 CST 2018
     */
    int updateByPrimaryKey(RuleTable record);
}