package com.sjjybsgj.rule_table.model;

import java.io.Serializable;

public class RuleTableWithBLOBs extends RuleTable implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_table.RANGE_VALUE
     *
     * @mbg.generated Mon May 28 15:03:50 CST 2018
     */
    private String rangeValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rule_table.COMPLEX
     *
     * @mbg.generated Mon May 28 15:03:50 CST 2018
     */
    private String complex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rule_table
     *
     * @mbg.generated Mon May 28 15:03:50 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_table.RANGE_VALUE
     *
     * @return the value of rule_table.RANGE_VALUE
     *
     * @mbg.generated Mon May 28 15:03:50 CST 2018
     */
    public String getRangeValue() {
        return rangeValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_table.RANGE_VALUE
     *
     * @param rangeValue the value for rule_table.RANGE_VALUE
     *
     * @mbg.generated Mon May 28 15:03:50 CST 2018
     */
    public void setRangeValue(String rangeValue) {
        this.rangeValue = rangeValue == null ? null : rangeValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rule_table.COMPLEX
     *
     * @return the value of rule_table.COMPLEX
     *
     * @mbg.generated Mon May 28 15:03:50 CST 2018
     */
    public String getComplex() {
        return complex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rule_table.COMPLEX
     *
     * @param complex the value for rule_table.COMPLEX
     *
     * @mbg.generated Mon May 28 15:03:50 CST 2018
     */
    public void setComplex(String complex) {
        this.complex = complex == null ? null : complex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rule_table
     *
     * @mbg.generated Mon May 28 15:03:50 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", rangeValue=").append(rangeValue);
        sb.append(", complex=").append(complex);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}