package com.sjjybsgj.source_db.model;

import java.util.ArrayList;
import java.util.List;

public class SourceDbExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table source_db
     *
     * @mbg.generated Sun May 27 20:58:43 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table source_db
     *
     * @mbg.generated Sun May 27 20:58:43 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table source_db
     *
     * @mbg.generated Sun May 27 20:58:43 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_db
     *
     * @mbg.generated Sun May 27 20:58:43 CST 2018
     */
    public SourceDbExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_db
     *
     * @mbg.generated Sun May 27 20:58:43 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_db
     *
     * @mbg.generated Sun May 27 20:58:43 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_db
     *
     * @mbg.generated Sun May 27 20:58:43 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_db
     *
     * @mbg.generated Sun May 27 20:58:43 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_db
     *
     * @mbg.generated Sun May 27 20:58:43 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_db
     *
     * @mbg.generated Sun May 27 20:58:43 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_db
     *
     * @mbg.generated Sun May 27 20:58:43 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_db
     *
     * @mbg.generated Sun May 27 20:58:43 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_db
     *
     * @mbg.generated Sun May 27 20:58:43 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_db
     *
     * @mbg.generated Sun May 27 20:58:43 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table source_db
     *
     * @mbg.generated Sun May 27 20:58:43 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDbSourceIdIsNull() {
            addCriterion("DB_SOURCE_ID is null");
            return (Criteria) this;
        }

        public Criteria andDbSourceIdIsNotNull() {
            addCriterion("DB_SOURCE_ID is not null");
            return (Criteria) this;
        }

        public Criteria andDbSourceIdEqualTo(String value) {
            addCriterion("DB_SOURCE_ID =", value, "dbSourceId");
            return (Criteria) this;
        }

        public Criteria andDbSourceIdNotEqualTo(String value) {
            addCriterion("DB_SOURCE_ID <>", value, "dbSourceId");
            return (Criteria) this;
        }

        public Criteria andDbSourceIdGreaterThan(String value) {
            addCriterion("DB_SOURCE_ID >", value, "dbSourceId");
            return (Criteria) this;
        }

        public Criteria andDbSourceIdGreaterThanOrEqualTo(String value) {
            addCriterion("DB_SOURCE_ID >=", value, "dbSourceId");
            return (Criteria) this;
        }

        public Criteria andDbSourceIdLessThan(String value) {
            addCriterion("DB_SOURCE_ID <", value, "dbSourceId");
            return (Criteria) this;
        }

        public Criteria andDbSourceIdLessThanOrEqualTo(String value) {
            addCriterion("DB_SOURCE_ID <=", value, "dbSourceId");
            return (Criteria) this;
        }

        public Criteria andDbSourceIdLike(String value) {
            addCriterion("DB_SOURCE_ID like", value, "dbSourceId");
            return (Criteria) this;
        }

        public Criteria andDbSourceIdNotLike(String value) {
            addCriterion("DB_SOURCE_ID not like", value, "dbSourceId");
            return (Criteria) this;
        }

        public Criteria andDbSourceIdIn(List<String> values) {
            addCriterion("DB_SOURCE_ID in", values, "dbSourceId");
            return (Criteria) this;
        }

        public Criteria andDbSourceIdNotIn(List<String> values) {
            addCriterion("DB_SOURCE_ID not in", values, "dbSourceId");
            return (Criteria) this;
        }

        public Criteria andDbSourceIdBetween(String value1, String value2) {
            addCriterion("DB_SOURCE_ID between", value1, value2, "dbSourceId");
            return (Criteria) this;
        }

        public Criteria andDbSourceIdNotBetween(String value1, String value2) {
            addCriterion("DB_SOURCE_ID not between", value1, value2, "dbSourceId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("USER_ID =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("USER_ID <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("USER_ID >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("USER_ID >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("USER_ID <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("USER_ID <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("USER_ID like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("USER_ID not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("USER_ID in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("USER_ID not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("USER_ID between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("USER_ID not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andConnectNameIsNull() {
            addCriterion("CONNECT_NAME is null");
            return (Criteria) this;
        }

        public Criteria andConnectNameIsNotNull() {
            addCriterion("CONNECT_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andConnectNameEqualTo(String value) {
            addCriterion("CONNECT_NAME =", value, "connectName");
            return (Criteria) this;
        }

        public Criteria andConnectNameNotEqualTo(String value) {
            addCriterion("CONNECT_NAME <>", value, "connectName");
            return (Criteria) this;
        }

        public Criteria andConnectNameGreaterThan(String value) {
            addCriterion("CONNECT_NAME >", value, "connectName");
            return (Criteria) this;
        }

        public Criteria andConnectNameGreaterThanOrEqualTo(String value) {
            addCriterion("CONNECT_NAME >=", value, "connectName");
            return (Criteria) this;
        }

        public Criteria andConnectNameLessThan(String value) {
            addCriterion("CONNECT_NAME <", value, "connectName");
            return (Criteria) this;
        }

        public Criteria andConnectNameLessThanOrEqualTo(String value) {
            addCriterion("CONNECT_NAME <=", value, "connectName");
            return (Criteria) this;
        }

        public Criteria andConnectNameLike(String value) {
            addCriterion("CONNECT_NAME like", value, "connectName");
            return (Criteria) this;
        }

        public Criteria andConnectNameNotLike(String value) {
            addCriterion("CONNECT_NAME not like", value, "connectName");
            return (Criteria) this;
        }

        public Criteria andConnectNameIn(List<String> values) {
            addCriterion("CONNECT_NAME in", values, "connectName");
            return (Criteria) this;
        }

        public Criteria andConnectNameNotIn(List<String> values) {
            addCriterion("CONNECT_NAME not in", values, "connectName");
            return (Criteria) this;
        }

        public Criteria andConnectNameBetween(String value1, String value2) {
            addCriterion("CONNECT_NAME between", value1, value2, "connectName");
            return (Criteria) this;
        }

        public Criteria andConnectNameNotBetween(String value1, String value2) {
            addCriterion("CONNECT_NAME not between", value1, value2, "connectName");
            return (Criteria) this;
        }

        public Criteria andDbNameIsNull() {
            addCriterion("DB_NAME is null");
            return (Criteria) this;
        }

        public Criteria andDbNameIsNotNull() {
            addCriterion("DB_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andDbNameEqualTo(String value) {
            addCriterion("DB_NAME =", value, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbNameNotEqualTo(String value) {
            addCriterion("DB_NAME <>", value, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbNameGreaterThan(String value) {
            addCriterion("DB_NAME >", value, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbNameGreaterThanOrEqualTo(String value) {
            addCriterion("DB_NAME >=", value, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbNameLessThan(String value) {
            addCriterion("DB_NAME <", value, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbNameLessThanOrEqualTo(String value) {
            addCriterion("DB_NAME <=", value, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbNameLike(String value) {
            addCriterion("DB_NAME like", value, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbNameNotLike(String value) {
            addCriterion("DB_NAME not like", value, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbNameIn(List<String> values) {
            addCriterion("DB_NAME in", values, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbNameNotIn(List<String> values) {
            addCriterion("DB_NAME not in", values, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbNameBetween(String value1, String value2) {
            addCriterion("DB_NAME between", value1, value2, "dbName");
            return (Criteria) this;
        }

        public Criteria andDbNameNotBetween(String value1, String value2) {
            addCriterion("DB_NAME not between", value1, value2, "dbName");
            return (Criteria) this;
        }

        public Criteria andIpIsNull() {
            addCriterion("IP is null");
            return (Criteria) this;
        }

        public Criteria andIpIsNotNull() {
            addCriterion("IP is not null");
            return (Criteria) this;
        }

        public Criteria andIpEqualTo(String value) {
            addCriterion("IP =", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotEqualTo(String value) {
            addCriterion("IP <>", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpGreaterThan(String value) {
            addCriterion("IP >", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpGreaterThanOrEqualTo(String value) {
            addCriterion("IP >=", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLessThan(String value) {
            addCriterion("IP <", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLessThanOrEqualTo(String value) {
            addCriterion("IP <=", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpLike(String value) {
            addCriterion("IP like", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotLike(String value) {
            addCriterion("IP not like", value, "ip");
            return (Criteria) this;
        }

        public Criteria andIpIn(List<String> values) {
            addCriterion("IP in", values, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotIn(List<String> values) {
            addCriterion("IP not in", values, "ip");
            return (Criteria) this;
        }

        public Criteria andIpBetween(String value1, String value2) {
            addCriterion("IP between", value1, value2, "ip");
            return (Criteria) this;
        }

        public Criteria andIpNotBetween(String value1, String value2) {
            addCriterion("IP not between", value1, value2, "ip");
            return (Criteria) this;
        }

        public Criteria andPortIsNull() {
            addCriterion("PORT is null");
            return (Criteria) this;
        }

        public Criteria andPortIsNotNull() {
            addCriterion("PORT is not null");
            return (Criteria) this;
        }

        public Criteria andPortEqualTo(Integer value) {
            addCriterion("PORT =", value, "port");
            return (Criteria) this;
        }

        public Criteria andPortNotEqualTo(Integer value) {
            addCriterion("PORT <>", value, "port");
            return (Criteria) this;
        }

        public Criteria andPortGreaterThan(Integer value) {
            addCriterion("PORT >", value, "port");
            return (Criteria) this;
        }

        public Criteria andPortGreaterThanOrEqualTo(Integer value) {
            addCriterion("PORT >=", value, "port");
            return (Criteria) this;
        }

        public Criteria andPortLessThan(Integer value) {
            addCriterion("PORT <", value, "port");
            return (Criteria) this;
        }

        public Criteria andPortLessThanOrEqualTo(Integer value) {
            addCriterion("PORT <=", value, "port");
            return (Criteria) this;
        }

        public Criteria andPortIn(List<Integer> values) {
            addCriterion("PORT in", values, "port");
            return (Criteria) this;
        }

        public Criteria andPortNotIn(List<Integer> values) {
            addCriterion("PORT not in", values, "port");
            return (Criteria) this;
        }

        public Criteria andPortBetween(Integer value1, Integer value2) {
            addCriterion("PORT between", value1, value2, "port");
            return (Criteria) this;
        }

        public Criteria andPortNotBetween(Integer value1, Integer value2) {
            addCriterion("PORT not between", value1, value2, "port");
            return (Criteria) this;
        }

        public Criteria andDbUserNameIsNull() {
            addCriterion("DB_USER_NAME is null");
            return (Criteria) this;
        }

        public Criteria andDbUserNameIsNotNull() {
            addCriterion("DB_USER_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andDbUserNameEqualTo(String value) {
            addCriterion("DB_USER_NAME =", value, "dbUserName");
            return (Criteria) this;
        }

        public Criteria andDbUserNameNotEqualTo(String value) {
            addCriterion("DB_USER_NAME <>", value, "dbUserName");
            return (Criteria) this;
        }

        public Criteria andDbUserNameGreaterThan(String value) {
            addCriterion("DB_USER_NAME >", value, "dbUserName");
            return (Criteria) this;
        }

        public Criteria andDbUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("DB_USER_NAME >=", value, "dbUserName");
            return (Criteria) this;
        }

        public Criteria andDbUserNameLessThan(String value) {
            addCriterion("DB_USER_NAME <", value, "dbUserName");
            return (Criteria) this;
        }

        public Criteria andDbUserNameLessThanOrEqualTo(String value) {
            addCriterion("DB_USER_NAME <=", value, "dbUserName");
            return (Criteria) this;
        }

        public Criteria andDbUserNameLike(String value) {
            addCriterion("DB_USER_NAME like", value, "dbUserName");
            return (Criteria) this;
        }

        public Criteria andDbUserNameNotLike(String value) {
            addCriterion("DB_USER_NAME not like", value, "dbUserName");
            return (Criteria) this;
        }

        public Criteria andDbUserNameIn(List<String> values) {
            addCriterion("DB_USER_NAME in", values, "dbUserName");
            return (Criteria) this;
        }

        public Criteria andDbUserNameNotIn(List<String> values) {
            addCriterion("DB_USER_NAME not in", values, "dbUserName");
            return (Criteria) this;
        }

        public Criteria andDbUserNameBetween(String value1, String value2) {
            addCriterion("DB_USER_NAME between", value1, value2, "dbUserName");
            return (Criteria) this;
        }

        public Criteria andDbUserNameNotBetween(String value1, String value2) {
            addCriterion("DB_USER_NAME not between", value1, value2, "dbUserName");
            return (Criteria) this;
        }

        public Criteria andDbPasswordIsNull() {
            addCriterion("DB_PASSWORD is null");
            return (Criteria) this;
        }

        public Criteria andDbPasswordIsNotNull() {
            addCriterion("DB_PASSWORD is not null");
            return (Criteria) this;
        }

        public Criteria andDbPasswordEqualTo(String value) {
            addCriterion("DB_PASSWORD =", value, "dbPassword");
            return (Criteria) this;
        }

        public Criteria andDbPasswordNotEqualTo(String value) {
            addCriterion("DB_PASSWORD <>", value, "dbPassword");
            return (Criteria) this;
        }

        public Criteria andDbPasswordGreaterThan(String value) {
            addCriterion("DB_PASSWORD >", value, "dbPassword");
            return (Criteria) this;
        }

        public Criteria andDbPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("DB_PASSWORD >=", value, "dbPassword");
            return (Criteria) this;
        }

        public Criteria andDbPasswordLessThan(String value) {
            addCriterion("DB_PASSWORD <", value, "dbPassword");
            return (Criteria) this;
        }

        public Criteria andDbPasswordLessThanOrEqualTo(String value) {
            addCriterion("DB_PASSWORD <=", value, "dbPassword");
            return (Criteria) this;
        }

        public Criteria andDbPasswordLike(String value) {
            addCriterion("DB_PASSWORD like", value, "dbPassword");
            return (Criteria) this;
        }

        public Criteria andDbPasswordNotLike(String value) {
            addCriterion("DB_PASSWORD not like", value, "dbPassword");
            return (Criteria) this;
        }

        public Criteria andDbPasswordIn(List<String> values) {
            addCriterion("DB_PASSWORD in", values, "dbPassword");
            return (Criteria) this;
        }

        public Criteria andDbPasswordNotIn(List<String> values) {
            addCriterion("DB_PASSWORD not in", values, "dbPassword");
            return (Criteria) this;
        }

        public Criteria andDbPasswordBetween(String value1, String value2) {
            addCriterion("DB_PASSWORD between", value1, value2, "dbPassword");
            return (Criteria) this;
        }

        public Criteria andDbPasswordNotBetween(String value1, String value2) {
            addCriterion("DB_PASSWORD not between", value1, value2, "dbPassword");
            return (Criteria) this;
        }

        public Criteria andDbTypeIsNull() {
            addCriterion("DB_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andDbTypeIsNotNull() {
            addCriterion("DB_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andDbTypeEqualTo(Integer value) {
            addCriterion("DB_TYPE =", value, "dbType");
            return (Criteria) this;
        }

        public Criteria andDbTypeNotEqualTo(Integer value) {
            addCriterion("DB_TYPE <>", value, "dbType");
            return (Criteria) this;
        }

        public Criteria andDbTypeGreaterThan(Integer value) {
            addCriterion("DB_TYPE >", value, "dbType");
            return (Criteria) this;
        }

        public Criteria andDbTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("DB_TYPE >=", value, "dbType");
            return (Criteria) this;
        }

        public Criteria andDbTypeLessThan(Integer value) {
            addCriterion("DB_TYPE <", value, "dbType");
            return (Criteria) this;
        }

        public Criteria andDbTypeLessThanOrEqualTo(Integer value) {
            addCriterion("DB_TYPE <=", value, "dbType");
            return (Criteria) this;
        }

        public Criteria andDbTypeIn(List<Integer> values) {
            addCriterion("DB_TYPE in", values, "dbType");
            return (Criteria) this;
        }

        public Criteria andDbTypeNotIn(List<Integer> values) {
            addCriterion("DB_TYPE not in", values, "dbType");
            return (Criteria) this;
        }

        public Criteria andDbTypeBetween(Integer value1, Integer value2) {
            addCriterion("DB_TYPE between", value1, value2, "dbType");
            return (Criteria) this;
        }

        public Criteria andDbTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("DB_TYPE not between", value1, value2, "dbType");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table source_db
     *
     * @mbg.generated do_not_delete_during_merge Sun May 27 20:58:43 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table source_db
     *
     * @mbg.generated Sun May 27 20:58:43 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}