package com.sjjybsgj.source_db.model;

import java.io.Serializable;

public class SourceDb implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source_db.DB_SOURCE_ID
     *
     * @mbg.generated Sun May 27 20:58:43 CST 2018
     */
    private String dbSourceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source_db.USER_ID
     *
     * @mbg.generated Sun May 27 20:58:43 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source_db.CONNECT_NAME
     *
     * @mbg.generated Sun May 27 20:58:43 CST 2018
     */
    private String connectName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source_db.DB_NAME
     *
     * @mbg.generated Sun May 27 20:58:43 CST 2018
     */
    private String dbName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source_db.IP
     *
     * @mbg.generated Sun May 27 20:58:43 CST 2018
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source_db.PORT
     *
     * @mbg.generated Sun May 27 20:58:43 CST 2018
     */
    private Integer port;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source_db.DB_USER_NAME
     *
     * @mbg.generated Sun May 27 20:58:43 CST 2018
     */
    private String dbUserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source_db.DB_PASSWORD
     *
     * @mbg.generated Sun May 27 20:58:43 CST 2018
     */
    private String dbPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column source_db.DB_TYPE
     *
     * @mbg.generated Sun May 27 20:58:43 CST 2018
     */
    private String dbType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table source_db
     *
     * @mbg.generated Sun May 27 20:58:43 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source_db.DB_SOURCE_ID
     *
     * @return the value of source_db.DB_SOURCE_ID
     *
     * @mbg.generated Sun May 27 20:58:43 CST 2018
     */
    public String getDbSourceId() {
        return dbSourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source_db.DB_SOURCE_ID
     *
     * @param dbSourceId the value for source_db.DB_SOURCE_ID
     *
     * @mbg.generated Sun May 27 20:58:43 CST 2018
     */
    public void setDbSourceId(String dbSourceId) {
        this.dbSourceId = dbSourceId == null ? null : dbSourceId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source_db.USER_ID
     *
     * @return the value of source_db.USER_ID
     *
     * @mbg.generated Sun May 27 20:58:43 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source_db.USER_ID
     *
     * @param userId the value for source_db.USER_ID
     *
     * @mbg.generated Sun May 27 20:58:43 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source_db.CONNECT_NAME
     *
     * @return the value of source_db.CONNECT_NAME
     *
     * @mbg.generated Sun May 27 20:58:43 CST 2018
     */
    public String getConnectName() {
        return connectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source_db.CONNECT_NAME
     *
     * @param connectName the value for source_db.CONNECT_NAME
     *
     * @mbg.generated Sun May 27 20:58:43 CST 2018
     */
    public void setConnectName(String connectName) {
        this.connectName = connectName == null ? null : connectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source_db.DB_NAME
     *
     * @return the value of source_db.DB_NAME
     *
     * @mbg.generated Sun May 27 20:58:43 CST 2018
     */
    public String getDbName() {
        return dbName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source_db.DB_NAME
     *
     * @param dbName the value for source_db.DB_NAME
     *
     * @mbg.generated Sun May 27 20:58:43 CST 2018
     */
    public void setDbName(String dbName) {
        this.dbName = dbName == null ? null : dbName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source_db.IP
     *
     * @return the value of source_db.IP
     *
     * @mbg.generated Sun May 27 20:58:43 CST 2018
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source_db.IP
     *
     * @param ip the value for source_db.IP
     *
     * @mbg.generated Sun May 27 20:58:43 CST 2018
     */
    public void setIp(String ip) {
        this.ip = ip == null ? null : ip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source_db.PORT
     *
     * @return the value of source_db.PORT
     *
     * @mbg.generated Sun May 27 20:58:43 CST 2018
     */
    public Integer getPort() {
        return port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source_db.PORT
     *
     * @param port the value for source_db.PORT
     *
     * @mbg.generated Sun May 27 20:58:43 CST 2018
     */
    public void setPort(Integer port) {
        this.port = port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source_db.DB_USER_NAME
     *
     * @return the value of source_db.DB_USER_NAME
     *
     * @mbg.generated Sun May 27 20:58:43 CST 2018
     */
    public String getDbUserName() {
        return dbUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source_db.DB_USER_NAME
     *
     * @param dbUserName the value for source_db.DB_USER_NAME
     *
     * @mbg.generated Sun May 27 20:58:43 CST 2018
     */
    public void setDbUserName(String dbUserName) {
        this.dbUserName = dbUserName == null ? null : dbUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source_db.DB_PASSWORD
     *
     * @return the value of source_db.DB_PASSWORD
     *
     * @mbg.generated Sun May 27 20:58:43 CST 2018
     */
    public String getDbPassword() {
        return dbPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source_db.DB_PASSWORD
     *
     * @param dbPassword the value for source_db.DB_PASSWORD
     *
     * @mbg.generated Sun May 27 20:58:43 CST 2018
     */
    public void setDbPassword(String dbPassword) {
        this.dbPassword = dbPassword == null ? null : dbPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column source_db.DB_TYPE
     *
     * @return the value of source_db.DB_TYPE
     *
     * @mbg.generated Sun May 27 20:58:43 CST 2018
     */
    public String getDbType() {
        return dbType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column source_db.DB_TYPE
     *
     * @param dbType the value for source_db.DB_TYPE
     *
     * @mbg.generated Sun May 27 20:58:43 CST 2018
     */
    public void setDbType(String dbType) {
        this.dbType = dbType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table source_db
     *
     * @mbg.generated Sun May 27 20:58:43 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", dbSourceId=").append(dbSourceId);
        sb.append(", userId=").append(userId);
        sb.append(", connectName=").append(connectName);
        sb.append(", dbName=").append(dbName);
        sb.append(", ip=").append(ip);
        sb.append(", port=").append(port);
        sb.append(", dbUserName=").append(dbUserName);
        sb.append(", dbPassword=").append(dbPassword);
        sb.append(", dbType=").append(dbType);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}