package com.sjjybsgj.update_log.mapper;

import com.sjjybsgj.update_log.model.UpdateLog;
import com.sjjybsgj.update_log.model.UpdateLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UpdateLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table update_log
     *
     * @mbg.generated Sun May 27 17:35:28 CST 2018
     */
    long countByExample(UpdateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table update_log
     *
     * @mbg.generated Sun May 27 17:35:28 CST 2018
     */
    int deleteByExample(UpdateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table update_log
     *
     * @mbg.generated Sun May 27 17:35:28 CST 2018
     */
    int deleteByPrimaryKey(String updateLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table update_log
     *
     * @mbg.generated Sun May 27 17:35:28 CST 2018
     */
    int insert(UpdateLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table update_log
     *
     * @mbg.generated Sun May 27 17:35:28 CST 2018
     */
    int insertSelective(UpdateLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table update_log
     *
     * @mbg.generated Sun May 27 17:35:28 CST 2018
     */
    List<UpdateLog> selectByExample(UpdateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table update_log
     *
     * @mbg.generated Sun May 27 17:35:28 CST 2018
     */
    UpdateLog selectByPrimaryKey(String updateLogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table update_log
     *
     * @mbg.generated Sun May 27 17:35:28 CST 2018
     */
    int updateByExampleSelective(@Param("record") UpdateLog record, @Param("example") UpdateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table update_log
     *
     * @mbg.generated Sun May 27 17:35:28 CST 2018
     */
    int updateByExample(@Param("record") UpdateLog record, @Param("example") UpdateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table update_log
     *
     * @mbg.generated Sun May 27 17:35:28 CST 2018
     */
    int updateByPrimaryKeySelective(UpdateLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table update_log
     *
     * @mbg.generated Sun May 27 17:35:28 CST 2018
     */
    int updateByPrimaryKey(UpdateLog record);
}