package com.sjjybsgj.checked_log.model;

import java.io.Serializable;
import java.util.Date;

public class CheckedLog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checked_log.LOG_ID
     *
     * @mbg.generated Tue May 29 15:51:56 CST 2018
     */
    private String logId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checked_log.USER_ID
     *
     * @mbg.generated Tue May 29 15:51:56 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checked_log.USER_NAME
     *
     * @mbg.generated Tue May 29 15:51:56 CST 2018
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checked_log.RULE_ID
     *
     * @mbg.generated Tue May 29 15:51:56 CST 2018
     */
    private String ruleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checked_log.TABLE_NAME
     *
     * @mbg.generated Tue May 29 15:51:56 CST 2018
     */
    private String tableName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checked_log.DB_NAME
     *
     * @mbg.generated Tue May 29 15:51:56 CST 2018
     */
    private String dbName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checked_log.CLOUMN_NAME
     *
     * @mbg.generated Tue May 29 15:51:56 CST 2018
     */
    private String cloumnName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checked_log.RULE_TYPE
     *
     * @mbg.generated Tue May 29 15:51:56 CST 2018
     */
    private String ruleType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checked_log.IF_PASS
     *
     * @mbg.generated Tue May 29 15:51:56 CST 2018
     */
    private Integer ifPass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checked_log.INFO
     *
     * @mbg.generated Tue May 29 15:51:56 CST 2018
     */
    private String info;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column checked_log.VAILD_DATE
     *
     * @mbg.generated Tue May 29 15:51:56 CST 2018
     */
    private Date vaildDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table checked_log
     *
     * @mbg.generated Tue May 29 15:51:56 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checked_log.LOG_ID
     *
     * @return the value of checked_log.LOG_ID
     *
     * @mbg.generated Tue May 29 15:51:56 CST 2018
     */
    public String getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checked_log.LOG_ID
     *
     * @param logId the value for checked_log.LOG_ID
     *
     * @mbg.generated Tue May 29 15:51:56 CST 2018
     */
    public void setLogId(String logId) {
        this.logId = logId == null ? null : logId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checked_log.USER_ID
     *
     * @return the value of checked_log.USER_ID
     *
     * @mbg.generated Tue May 29 15:51:56 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checked_log.USER_ID
     *
     * @param userId the value for checked_log.USER_ID
     *
     * @mbg.generated Tue May 29 15:51:56 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checked_log.USER_NAME
     *
     * @return the value of checked_log.USER_NAME
     *
     * @mbg.generated Tue May 29 15:51:56 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checked_log.USER_NAME
     *
     * @param userName the value for checked_log.USER_NAME
     *
     * @mbg.generated Tue May 29 15:51:56 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checked_log.RULE_ID
     *
     * @return the value of checked_log.RULE_ID
     *
     * @mbg.generated Tue May 29 15:51:56 CST 2018
     */
    public String getRuleId() {
        return ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checked_log.RULE_ID
     *
     * @param ruleId the value for checked_log.RULE_ID
     *
     * @mbg.generated Tue May 29 15:51:56 CST 2018
     */
    public void setRuleId(String ruleId) {
        this.ruleId = ruleId == null ? null : ruleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checked_log.TABLE_NAME
     *
     * @return the value of checked_log.TABLE_NAME
     *
     * @mbg.generated Tue May 29 15:51:56 CST 2018
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checked_log.TABLE_NAME
     *
     * @param tableName the value for checked_log.TABLE_NAME
     *
     * @mbg.generated Tue May 29 15:51:56 CST 2018
     */
    public void setTableName(String tableName) {
        this.tableName = tableName == null ? null : tableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checked_log.DB_NAME
     *
     * @return the value of checked_log.DB_NAME
     *
     * @mbg.generated Tue May 29 15:51:56 CST 2018
     */
    public String getDbName() {
        return dbName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checked_log.DB_NAME
     *
     * @param dbName the value for checked_log.DB_NAME
     *
     * @mbg.generated Tue May 29 15:51:56 CST 2018
     */
    public void setDbName(String dbName) {
        this.dbName = dbName == null ? null : dbName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checked_log.CLOUMN_NAME
     *
     * @return the value of checked_log.CLOUMN_NAME
     *
     * @mbg.generated Tue May 29 15:51:56 CST 2018
     */
    public String getCloumnName() {
        return cloumnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checked_log.CLOUMN_NAME
     *
     * @param cloumnName the value for checked_log.CLOUMN_NAME
     *
     * @mbg.generated Tue May 29 15:51:56 CST 2018
     */
    public void setCloumnName(String cloumnName) {
        this.cloumnName = cloumnName == null ? null : cloumnName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checked_log.RULE_TYPE
     *
     * @return the value of checked_log.RULE_TYPE
     *
     * @mbg.generated Tue May 29 15:51:56 CST 2018
     */
    public String getRuleType() {
        return ruleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checked_log.RULE_TYPE
     *
     * @param ruleType the value for checked_log.RULE_TYPE
     *
     * @mbg.generated Tue May 29 15:51:56 CST 2018
     */
    public void setRuleType(String ruleType) {
        this.ruleType = ruleType == null ? null : ruleType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checked_log.IF_PASS
     *
     * @return the value of checked_log.IF_PASS
     *
     * @mbg.generated Tue May 29 15:51:56 CST 2018
     */
    public Integer getIfPass() {
        return ifPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checked_log.IF_PASS
     *
     * @param ifPass the value for checked_log.IF_PASS
     *
     * @mbg.generated Tue May 29 15:51:56 CST 2018
     */
    public void setIfPass(Integer ifPass) {
        this.ifPass = ifPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checked_log.INFO
     *
     * @return the value of checked_log.INFO
     *
     * @mbg.generated Tue May 29 15:51:56 CST 2018
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checked_log.INFO
     *
     * @param info the value for checked_log.INFO
     *
     * @mbg.generated Tue May 29 15:51:56 CST 2018
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column checked_log.VAILD_DATE
     *
     * @return the value of checked_log.VAILD_DATE
     *
     * @mbg.generated Tue May 29 15:51:56 CST 2018
     */
    public Date getVaildDate() {
        return vaildDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column checked_log.VAILD_DATE
     *
     * @param vaildDate the value for checked_log.VAILD_DATE
     *
     * @mbg.generated Tue May 29 15:51:56 CST 2018
     */
    public void setVaildDate(Date vaildDate) {
        this.vaildDate = vaildDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table checked_log
     *
     * @mbg.generated Tue May 29 15:51:56 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", logId=").append(logId);
        sb.append(", userId=").append(userId);
        sb.append(", userName=").append(userName);
        sb.append(", ruleId=").append(ruleId);
        sb.append(", tableName=").append(tableName);
        sb.append(", dbName=").append(dbName);
        sb.append(", cloumnName=").append(cloumnName);
        sb.append(", ruleType=").append(ruleType);
        sb.append(", ifPass=").append(ifPass);
        sb.append(", info=").append(info);
        sb.append(", vaildDate=").append(vaildDate);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}