package com.sjjybsgj.update_log.model;

import java.io.Serializable;
import java.util.Date;

public class UpdateLog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column update_log.UPDATE_LOG_ID
     *
     * @mbg.generated Sun May 27 17:35:28 CST 2018
     */
    private String updateLogId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column update_log.USER_ID
     *
     * @mbg.generated Sun May 27 17:35:28 CST 2018
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column update_log.USER_NAME
     *
     * @mbg.generated Sun May 27 17:35:28 CST 2018
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column update_log.DB_NAME
     *
     * @mbg.generated Sun May 27 17:35:28 CST 2018
     */
    private String dbName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column update_log.TABLE_NAME
     *
     * @mbg.generated Sun May 27 17:35:28 CST 2018
     */
    private String tableName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column update_log.UPDATE_DATE
     *
     * @mbg.generated Sun May 27 17:35:28 CST 2018
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column update_log.IF_PASS
     *
     * @mbg.generated Sun May 27 17:35:28 CST 2018
     */
    private Integer ifPass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column update_log.INFO
     *
     * @mbg.generated Sun May 27 17:35:28 CST 2018
     */
    private String info;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table update_log
     *
     * @mbg.generated Sun May 27 17:35:28 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column update_log.UPDATE_LOG_ID
     *
     * @return the value of update_log.UPDATE_LOG_ID
     *
     * @mbg.generated Sun May 27 17:35:28 CST 2018
     */
    public String getUpdateLogId() {
        return updateLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column update_log.UPDATE_LOG_ID
     *
     * @param updateLogId the value for update_log.UPDATE_LOG_ID
     *
     * @mbg.generated Sun May 27 17:35:28 CST 2018
     */
    public void setUpdateLogId(String updateLogId) {
        this.updateLogId = updateLogId == null ? null : updateLogId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column update_log.USER_ID
     *
     * @return the value of update_log.USER_ID
     *
     * @mbg.generated Sun May 27 17:35:28 CST 2018
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column update_log.USER_ID
     *
     * @param userId the value for update_log.USER_ID
     *
     * @mbg.generated Sun May 27 17:35:28 CST 2018
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column update_log.USER_NAME
     *
     * @return the value of update_log.USER_NAME
     *
     * @mbg.generated Sun May 27 17:35:28 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column update_log.USER_NAME
     *
     * @param userName the value for update_log.USER_NAME
     *
     * @mbg.generated Sun May 27 17:35:28 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column update_log.DB_NAME
     *
     * @return the value of update_log.DB_NAME
     *
     * @mbg.generated Sun May 27 17:35:28 CST 2018
     */
    public String getDbName() {
        return dbName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column update_log.DB_NAME
     *
     * @param dbName the value for update_log.DB_NAME
     *
     * @mbg.generated Sun May 27 17:35:28 CST 2018
     */
    public void setDbName(String dbName) {
        this.dbName = dbName == null ? null : dbName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column update_log.TABLE_NAME
     *
     * @return the value of update_log.TABLE_NAME
     *
     * @mbg.generated Sun May 27 17:35:28 CST 2018
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column update_log.TABLE_NAME
     *
     * @param tableName the value for update_log.TABLE_NAME
     *
     * @mbg.generated Sun May 27 17:35:28 CST 2018
     */
    public void setTableName(String tableName) {
        this.tableName = tableName == null ? null : tableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column update_log.UPDATE_DATE
     *
     * @return the value of update_log.UPDATE_DATE
     *
     * @mbg.generated Sun May 27 17:35:28 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column update_log.UPDATE_DATE
     *
     * @param updateDate the value for update_log.UPDATE_DATE
     *
     * @mbg.generated Sun May 27 17:35:28 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column update_log.IF_PASS
     *
     * @return the value of update_log.IF_PASS
     *
     * @mbg.generated Sun May 27 17:35:28 CST 2018
     */
    public Integer getIfPass() {
        return ifPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column update_log.IF_PASS
     *
     * @param ifPass the value for update_log.IF_PASS
     *
     * @mbg.generated Sun May 27 17:35:28 CST 2018
     */
    public void setIfPass(Integer ifPass) {
        this.ifPass = ifPass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column update_log.INFO
     *
     * @return the value of update_log.INFO
     *
     * @mbg.generated Sun May 27 17:35:28 CST 2018
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column update_log.INFO
     *
     * @param info the value for update_log.INFO
     *
     * @mbg.generated Sun May 27 17:35:28 CST 2018
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table update_log
     *
     * @mbg.generated Sun May 27 17:35:28 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", updateLogId=").append(updateLogId);
        sb.append(", userId=").append(userId);
        sb.append(", userName=").append(userName);
        sb.append(", dbName=").append(dbName);
        sb.append(", tableName=").append(tableName);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", ifPass=").append(ifPass);
        sb.append(", info=").append(info);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}